name = "fair"
run = "docker run --rm -v \"$PWD/run:/run\" ${IMAGE} ${ARGS}"
image = "fair-runner:local"
args = ["--in", "{input:fair_input}", "--out", "{output:output_data}"]

[[inputs]]
# TODO: this should eventually support URLs as well as local files
name = "fair_input"

[inputs.schema]
type = "object"
required = []


[[outputs]]
name = "output_data"

[outputs.schema]
type = "object"
required = ["timebounds", "scenarios", "configs", "temperature_K", "co2_ppm", "forcing_sum_Wm2"]
