name = "fair"
run = "docker run --rm -v \"$PWD/run:/run\" ${IMAGE} ${ARGS} > run/climate_projections.output.json"

image = "fair-runner:local"
args = ["{input:emissions}"]

[[inputs]]
# TODO: this should eventually support URLs as well as local files
name = "emissions"

[inputs.schema]
type = "object"
required = []


[[outputs]]
name = "climate_projections"


[outputs.schema]
type = "object"
required = ["timebounds", "scenarios", "configs", "temperature_K", "co2_ppm", "forcing_sum_Wm2"]
